import { FlatList, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useStudy } from "@/lib/study-provider";

export default function ProgressScreen() {
  const { history } = useStudy();
  const latest = history[0];
  const correct = latest?.score ?? 0;
  const accuracy = latest ? Math.round((correct / Math.max(1, latest.problemIds.length)) * 100) : 0;
  return <ScreenContainer className="px-5"><FlatList data={history} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.title}>학습 기록</Text><Text style={styles.subtitle}>쌓인 풀이가 실력을 만듭니다.</Text><View style={styles.insight}><Text style={styles.insightKicker}>최근 성과</Text><Text style={styles.insightScore}>{latest ? `${accuracy}%` : "시작해볼까요?"}</Text><Text style={styles.insightBody}>{latest ? `${latest.title}에서 ${correct}문제를 맞혔어요.` : "첫 시험을 치르면 이곳에서 성과를 확인할 수 있어요."}</Text></View><View style={styles.metricRow}><View style={styles.metric}><Text style={styles.metricValue}>{history.length}</Text><Text style={styles.metricLabel}>누적 응시</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{latest ? `${correct}/${latest.problemIds.length}` : "—"}</Text><Text style={styles.metricLabel}>최근 정답</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{latest ? `${Math.max(1, Math.ceil(latest.durationSeconds / 60))}분` : "—"}</Text><Text style={styles.metricLabel}>최근 시간</Text></View></View><Text style={styles.sectionTitle}>최근 시험</Text></>} ListEmptyComponent={<View style={styles.empty}><IconSymbol name="chart.bar.fill" size={36} color="#8791A5" /><Text style={styles.emptyText}>아직 기록된 시험이 없어요.</Text></View>} renderItem={({ item }) => <View style={styles.historyCard}><View style={styles.historyIcon}><IconSymbol name="checkmark.circle.fill" size={19} color="#3653E8" /></View><View style={styles.historyInfo}><Text style={styles.historyTitle}>{item.title}</Text><Text style={styles.historyDate}>{new Date(item.submittedAt).toLocaleDateString("ko-KR")} · {Math.max(1, Math.ceil(item.durationSeconds / 60))}분</Text></View><Text style={styles.historyScore}>{item.score}/{item.problemIds.length}</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingTop: 16, paddingBottom: 24 }, title: { color: "#1D2433", fontSize: 27, lineHeight: 34, fontWeight: "900", letterSpacing: -0.6 }, subtitle: { color: "#697386", fontSize: 14, lineHeight: 21, marginTop: 5 }, insight: { backgroundColor: "#263877", borderRadius: 22, padding: 21, marginTop: 24 }, insightKicker: { color: "#BFC9FF", fontSize: 12, fontWeight: "800" }, insightScore: { color: "#FFFFFF", fontSize: 32, lineHeight: 40, fontWeight: "900", marginTop: 6 }, insightBody: { color: "#D7DDFF", fontSize: 13, lineHeight: 19, marginTop: 4 }, metricRow: { flexDirection: "row", gap: 10, marginTop: 12, marginBottom: 27 }, metric: { flex: 1, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E8F0", paddingVertical: 14, borderRadius: 16 }, metricValue: { color: "#1D2433", textAlign: "center", fontSize: 18, fontWeight: "800" }, metricLabel: { color: "#7B879C", textAlign: "center", fontSize: 11, marginTop: 5, fontWeight: "700" }, sectionTitle: { color: "#1D2433", fontSize: 18, fontWeight: "800", marginBottom: 11 }, empty: { backgroundColor: "#FFFFFF", padding: 28, borderRadius: 19, alignItems: "center", borderWidth: 1, borderColor: "#E5E8F0" }, emptyText: { color: "#697386", fontSize: 14, fontWeight: "700", marginTop: 10 }, historyCard: { minHeight: 68, padding: 13, borderRadius: 17, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E8F0", flexDirection: "row", alignItems: "center", marginBottom: 9 }, historyIcon: { width: 35, height: 35, borderRadius: 12, backgroundColor: "#E8EDFF", justifyContent: "center", alignItems: "center", marginRight: 10 }, historyInfo: { flex: 1 }, historyTitle: { color: "#344054", fontSize: 14, fontWeight: "800" }, historyDate: { color: "#8791A5", fontSize: 11, marginTop: 4, fontWeight: "600" }, historyScore: { color: "#3653E8", fontSize: 16, fontWeight: "900" },
});

