import { useRouter } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { haptic } from "@/lib/haptics";
import { useStudy } from "@/lib/study-provider";

export default function ReviewScreen() {
  const router = useRouter();
  const { history, libraryProblems } = useStudy();
  const latest = history[0];
  const items = (latest?.problemIds ?? []).map((id) => libraryProblems.find((problem) => problem.id === id)).filter((problem): problem is NonNullable<typeof problem> => Boolean(problem)).filter((problem) => latest?.attempts.find((attempt) => attempt.problemId === problem.id && !attempt.isCorrect));

  return <ScreenContainer className="px-5"><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.title}>복습</Text><Text style={styles.subtitle}>기억이 흐려지기 전에 오답을 다시 풀어보세요.</Text><View style={styles.summary}><View style={styles.summaryIcon}><IconSymbol name="flag.fill" size={20} color="#E45A4E" /></View><View><Text style={styles.summaryTitle}>{latest ? `${items.length}개의 문제를 다시 볼 차례예요` : "아직 복습할 문제가 없어요"}</Text><Text style={styles.summaryBody}>{latest ? "최근 시험에서 놓친 개념만 모아두었어요." : "시험을 응시하면 오답이 이곳에 모여요."}</Text></View></View><Text style={styles.sectionTitle}>{items.length ? "다시 풀 문제" : "복습 안내"}</Text></>} ListEmptyComponent={<View style={styles.empty}><IconSymbol name="checkmark.circle.fill" size={35} color="#0F9F78" /><Text style={styles.emptyTitle}>지금은 복습이 비어 있어요</Text><Text style={styles.emptyBody}>오늘의 테스트를 풀면 꼭 다시 볼 문제를 골라드릴게요.</Text><Pressable onPress={() => router.push("/exam" as never)} style={({ pressed }) => [styles.startButton, pressed && styles.pressed]}><Text style={styles.startText}>시험 시작하기</Text></Pressable></View>} renderItem={({ item }) => <Pressable onPress={() => { haptic.light(); router.push(`/review/${item.id}` as never); }} style={({ pressed }) => [styles.reviewCard, pressed && styles.pressed]}><View style={styles.cardTop}><Text style={styles.subject}>{item.subject} · {item.label}</Text><IconSymbol name="chevron.right" size={20} color="#8791A5" /></View><Text style={styles.question} numberOfLines={2}>{item.question}</Text><View style={styles.cardBottom}><Text style={styles.tryAgain}>다시 풀기</Text><Text style={styles.explanation}>해설 포함</Text></View></Pressable>} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingTop: 16, paddingBottom: 24 }, title: { color: "#1D2433", fontSize: 27, lineHeight: 34, fontWeight: "900", letterSpacing: -0.6 }, subtitle: { color: "#697386", fontSize: 14, lineHeight: 21, marginTop: 5 }, summary: { padding: 17, backgroundColor: "#FFF1EE", borderRadius: 18, marginTop: 24, marginBottom: 26, flexDirection: "row", gap: 12, alignItems: "center" }, summaryIcon: { width: 39, height: 39, borderRadius: 14, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, summaryTitle: { color: "#793B36", fontSize: 14, fontWeight: "800" }, summaryBody: { color: "#985E58", fontSize: 12, marginTop: 3 }, sectionTitle: { color: "#1D2433", fontSize: 18, fontWeight: "800", marginBottom: 11 }, reviewCard: { padding: 17, borderRadius: 18, borderWidth: 1, borderColor: "#E5E8F0", backgroundColor: "#FFFFFF", marginBottom: 10 }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }, subject: { color: "#E45A4E", fontSize: 12, fontWeight: "800" }, question: { color: "#344054", fontSize: 15, lineHeight: 22, fontWeight: "800" }, cardBottom: { marginTop: 14, flexDirection: "row", justifyContent: "space-between" }, tryAgain: { color: "#3653E8", fontSize: 12, fontWeight: "800" }, explanation: { color: "#8791A5", fontSize: 12, fontWeight: "700" }, empty: { backgroundColor: "#FFFFFF", alignItems: "center", borderRadius: 20, borderWidth: 1, borderColor: "#E5E8F0", paddingHorizontal: 26, paddingVertical: 32 }, emptyTitle: { color: "#1D2433", fontSize: 17, fontWeight: "800", marginTop: 13 }, emptyBody: { color: "#697386", fontSize: 13, textAlign: "center", lineHeight: 19, marginTop: 7 }, startButton: { marginTop: 20, height: 48, paddingHorizontal: 18, borderRadius: 14, justifyContent: "center", backgroundColor: "#3653E8" }, startText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
});
